graph TB
  node6["0"]
  style node6 fill:lightgray
  node7["1"]
  style node7 fill:lightgray
  u("u")
  v("v")
  x("x")
  y("y")
  y("y")
  u --> node7
  u --> v
  v --> node6
  v --> node7
  x --> y
  x --> y
  y --> node6
  y --> node6
  y --> u
  y --> u
